name: Rust Multi-Arch Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build-linux-x86_64:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Upload Asset
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./target/x86_64-unknown-linux-gnu/release/Rstream
        asset_name: Rstream-x86_64

  build-linux-aarch64:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true
    - name: Install cross-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y clang gcc-aarch64-linux-gnu
    - name: Build
      run: cargo build --release --target aarch64-unknown-linux-gnu
    - name: Upload Asset
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./target/aarch64-unknown-linux-gnu/release/Rstream
        asset_name: Rstream-aarch64

  build-linux-riscv64:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: riscv64gc-unknown-linux-gnu
        override: true
    - name: Install cross-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y clang gcc-riscv64-linux-gnu
    - name: Build
      run: cargo build --release --target riscv64gc-unknown-linux-gnu
    - name: Upload Asset
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./target/riscv64gc-unknown-linux-gnu/release/Rstream
        asset_name: Rstream-riscv64
